spring:
  application:
    name:marketplace-product-parser

file-processing:
  input-dir: "C:/myData/marketplace-product-parser/data/input-folder"
  processed-dir: "C:/myData/marketplace-product-parser/data/processed-folder"
  failed-dir: "C:/myData/marketplace-product-parser/data/failed-folder"
  cron: "* */5 * * * *"
  thread-pool-size: 10
  max-export-age-days: 30

